config/routes.rb
Objectives::Application.routes.draw do
  resources :stems

  devise_for :users
  resources :responses

  resources :exams

  resources :objectives

  get "about/index"

  root :to => "responses#new"

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_many :stems
  has_many :objectives
end

app/models/objective.rb
class Objective < ActiveRecord::Base
  has_many :responses
  belongs_to :exam
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
  has_one :objective
  has_one :stem
end

app/models/stem.rb
class Stem < ActiveRecord::Base
  belongs_to :exam
  has_many :objectives
  has_many :responses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #User-Response relationship 
  has_many :responses

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  def index
    @exams = Exam.all
  end

  def show
    @stems = Stem.where(:exam_id => @exam.id)
    @objectives = Objective.where(:exam_id => @exam.id)

  end

  def new
    @exam = Exam.new
  end

  def edit
  end

  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render action: 'show', status: :created, location: @exam }
      else
        format.html { render action: 'new' }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:content, :examday, :objective_id, :stem_id)
    end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: [:show, :edit, :update, :destroy]

  def index
    @objectives = Objective.all
    @exams = Exam.all
  end

  def show
  end

  def new
    @objective = Objective.new
    @exams = Exam.all
  end

  def edit
  end

  def create
    @objective = Objective.new(objective_params)

    respond_to do |format|
      if @objective.save
        format.html { redirect_to @objective, notice: 'Objective was successfully created.' }
        format.json { render action: 'show', status: :created, location: @objective }
      else
        format.html { render action: 'new' }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to @objective, notice: 'Objective was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @objective.destroy
    respond_to do |format|
      format.html { redirect_to objectives_url }
      format.json { head :no_content }
    end
  end

  private
    def set_objective
      @objective = Objective.find(params[:id])
    end

    def objective_params
      params.require(:objective).permit(:objective, :stem_id, :exam_id, :strength_id)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  def index
    @responses = Response.all
  end

  def show
    @stem = Stem.find(:first, :conditions => { :id => @response.stem_id })
    @objective = Objective.find(:first, :conditions => { :id => @response.objective_id })
  end

  def new
    @response = Response.new
    ### ideally here would be the filtering for the stems....?
    @stem = Stem.random
    @objectives = Objective.where(:exam_id => @stem.exam_id)
  end

  def edit
  end

  def create
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        format.html { redirect_to @response, notice: 'Response was successfully created.' }
        format.json { render action: 'show', status: :created, location: @response }
      else
        format.html { render action: 'new' }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:user_id, :objective_id, :stem_id, :strength)
    end
end

app/controllers/stems_controller.rb
class StemsController < ApplicationController
  before_action :set_stem, only: [:show, :edit, :update, :destroy]

  # GET /stems
  # GET /stems.json
  def index
    @stems = Stem.all
  end

  # GET /stems/1
  # GET /stems/1.json
  def show
  end

  # GET /stems/new
  def new
    @stem = Stem.new
    @exams = Exam.all
  end

  # GET /stems/1/edit
  def edit
  end

  # POST /stems
  # POST /stems.json
  def create
    @stem = Stem.new(stem_params)

    respond_to do |format|
      if @stem.save
        format.html { redirect_to @stem, notice: 'Stem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stem }
      else
        format.html { render action: 'new' }
        format.json { render json: @stem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stems/1
  # PATCH/PUT /stems/1.json
  def update
    respond_to do |format|
      if @stem.update(stem_params)
        format.html { redirect_to @stem, notice: 'Stem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stems/1
  # DELETE /stems/1.json
  def destroy
    @stem.destroy
    respond_to do |format|
      format.html { redirect_to stems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stem
      @stem = Stem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stem_params
      params.require(:stem).permit(:content, :exam_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/stems_helper.rb
module StemsHelper
end

app/views/about/index.html.erb
<div class="jumbotron">
<center>
	<h3>The major players in Type I hypersensitivity are:</h3>
	<br>
	<table>
		<tr><td><h4>Objective: &nbsp;</h4></td><td><select><option value="test1">Test 1</option>
  													<option value="test2">Test 2</option>
  													<option value="test3">Test 3</option>
  													<option value="test4">Test 4</option></select></td></tr>
		<tr><td><h4>Strength:</h4></td><td>1-5</td></tr>
	</table>
  <br><br>
  <p><a class="btn btn-primary btn-lg" role="button">Submit!</a></p>
</center>
</div>

app/views/exams/_form.html.erb
<%= simple_form_for(@exam) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
	<tr><td><strong>Title</strong></td><td><div class="field"><%= f.text_field :content %></div></td></tr>
	<tr><td><strong>Date</strong></td><td><div class="field"><%= f.text_field :examday %></div></td></tr>
</table>
<br>
<center>
<%= f.button :submit, "Create", :class => "btn btn-primary" %>
</center>
<br>

<br>
<!--
  <div class="field">
    <%= f.label :objective_id %><br>
    <%= f.number_field :objective_id %>
  </div>
  <div class="field">
    <%= f.label :stem_id %><br>
    <%= f.number_field :stem_id %>
  </div>

-->
<% end %>

app/views/exams/edit.html.erb
<h1>Editing exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<center><h3>Exams</h3></center>

<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th>Date</th>
      <th></th>
	<% if user_signed_in? %>
	<% if current_user.is_admin == 1 %>
      <th></th>
	  <th></th>
	<% else %>
	<% end %>
	<% else %>
	<% end %>
  </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.content %></td>
        <td><%= exam.examday %></td>
        <td><%= link_to 'Analyze', exam, :class => "btn btn-danger" %></td>
		<% if user_signed_in? %>
		<% if current_user.is_admin == 1 %>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Delete', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% else %>
		<% end %>
		<% else %>
		<% end %>  
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<center><%= link_to 'New Exam', new_exam_path, :class => "btn btn-primary" %></center>

app/views/exams/new.html.erb
<center>
<h3>Create a new exam!</h3>
</center>

<%= render 'form' %>

<!-- Hide back path for the time being...
<%= link_to 'Back', exams_path %>
-->

app/views/exams/show.html.erb
<center><h3><%= @exam.content %><br><small><%= @exam.examday %></small></h3></center>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Question</th>
	  <center>
	  <th>Objective - Rater 1</th>
	  <th>Objective - Rater 2</th>
	  <th>Agree?</th>
	  <th>Strength - Rater 1</th>
	  <th>Strength - Rater 2</th>
	  </center>
    </tr>
  </thead>
  <tbody>
    <% @stems.each do |stem| %>
      <tr>
        <td><%= stem.content %></td>
	  	<% responses = Response.where(:stem_id => stem.id).order("created_at").last(2)%>
		<% objarray = [] %>
			<% responses.each do |response| %>
				<td> <%= response.objective_id %></td>
				<% objarray.push(response.objective_id) %>
			<% end %>
			
			<% if objarray[0] == objarray[1] %>
			<td><span class="glyphicon glyphicon-ok"></span></td>		
			<% else %>
			<td>fail</td>
			<% end %>
			
			<% responses.each do |response| %>
				<td> <%= response.strength %></td>
			<% end %>		
      </tr>
    <% end %>
  	</tbody>
</table>


<br><br>
<%= link_to 'Back', exams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Objective Mapper</title>

  <!-- Latest compiled and minified Bootstrap CSS, courtesy of MaxCDN -->
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<!-- Add code for nav bar -->

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-resize-small"></span> <strong>Objective Mapper</strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

	  <ul class="nav navbar-nav navbar-left">
	  </ul>
      <ul class="nav navbar-nav navbar-right">
	    <li><a href="/exams">Exams</a></li>
	    <li><a href="/objectives">Objectives</a></li>
        <li><a href="/stems/new">New Question</a></li>
		<% if user_signed_in? %>
		<li><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></li>
		<% else %>
		<li><a href="/users/sign_in"><strong>Log In</strong></a></li>
		<% end %>
      </ul>
    </div>
  </div>
</nav>

<!--Flash messages -->
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<!-- Render! -->
<div class="jumbotron">
<%= yield %>
</div>
<!-- Add code for footer-->
</div>
</body>
</html>

app/views/objectives/_form.html.erb
<%= simple_form_for(@objective) do |f| %>
  <% if @objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
      <% @objective.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
	<tr><td><strong>Exam</strong></td><td><%= f.input :exam_id, as: :select, collection: @exams, :label_method => :content, :value_method => :id, label:false %></td></tr>
	<tr><td><strong>Objective</strong></td><td><%= f.text_field :objective %></td></tr>
	<tr></tr>
</table>
<br>
<center>
<%= f.button :submit, "Create Objective", :class => "btn btn-primary" %>
</center>
<br>
<% end %>

app/views/objectives/edit.html.erb
<h1>Editing objective</h1>

<%= render 'form' %>

<%= link_to 'Show', @objective %> |
<%= link_to 'Back', objectives_path %>

app/views/objectives/index.html.erb
<center><h3>Objectives</h3></center>

<table class="table">
  <thead>
    <tr>
      <th>Objective</th>
      <th>Exam</th>
	<% if user_signed_in? %>
	<% if current_user.is_admin == 1 %>
      <th></th>
      <th></th>
      <th></th>
	<% else%>
	<% end %>
	<% else %>
	<% end %>
    </tr>
  </thead>

  <tbody>
    <% @objectives.each do |objective| %>
      <tr>
        <td><%= objective.objective %></td>
		<% exam = Exam.find(objective.exam_id) %>
	    <td><%= exam.content %></td>
	<% if user_signed_in? %>
	<% if current_user.is_admin == 1 %>
        <td><%= link_to 'Show', objective %></td>
        <td><%= link_to 'Edit', edit_objective_path(objective) %></td>
        <td><%= link_to 'Destroy', objective, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% else %>
	<% end %>
	<% else %>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<center><%= link_to 'New Objective', new_objective_path, :class => "btn btn-primary" %></center>

app/views/objectives/new.html.erb
<center>
<h3>Create new learning objectives!</h3>
</center>

<%= render 'form' %>

<!-- Hide back links for the time being.... 
<%= link_to 'Back', objectives_path %>
-->

app/views/objectives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Objective:</strong>
  <%= @objective.objective %>
</p>

<p>
  <strong>Exam:</strong>
  <%= @objective.exam_id %>
</p>

<%= link_to 'Edit', edit_objective_path(@objective) %> |
<%= link_to 'Back', objectives_path %>

app/views/responses/_form.html.erb
<%= simple_form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<center>
<table class="table">
	<tr><td><strong>What lecture objective does this question address?</strong></td><td><%= f.input :objective_id, as: :select, collection: @objectives, :label_method => :objective, :value_method => :id, label:false %></td></tr>
	<tr><td><strong>How strong is the association? <br>(1 = very weak, 5 = very strong)</strong></td><td><%= f.input :strength, collection:1..5, label:false %></td></tr>
	<%= f.input :stem_id, :as => :hidden, :input_html => {:value => @stem.id } %>
	
	<% if user_signed_in? %>
	<%= f.input :user_id, :as => :hidden, :input_html => {:value => current_user.id } %>
	<% else %>
	<%= f.input :user_id, :as => :hidden, :input_html => {:value => 0 } %>
	<% end %>
	
</table>
</center>
<br>
<center>
<%= f.button :submit, "Submit!", :class => "btn btn-primary" %>
</center>
<br>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<center><h3>Responses</h3></center>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Stem</th>
      <th>Objective</th>
      <th>Strength</th>
	<% if user_signed_in? %>
	<% if current_user.is_admin == 1 %>
      <th></th>
      <th></th>
      <th></th>
	<% else %>
	<% end %>
	<% else %>
	<% end %>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.user_id %></td>
        <td><%= response.stem_id %></td>
        <td><%= response.objective_id %></td>
        <td><%= response.strength %></td>
	<% if user_signed_in? %>
	<% if current_user.is_admin == 1 %>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% else %>
	<% end %>
	<% else %>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<center><%= link_to 'New Response', new_response_path, :class => "btn btn-primary" %></center>

app/views/responses/new.html.erb
<center><h3><%= @stem.content %></h3></center>
<br>
<%= render 'form' %>

<!-- Hide link for now... 
<%= link_to 'Back', responses_path %>
-->

app/views/responses/show.html.erb
<center><h3>Thanks for submitting a response!</h3></center>

<p>
  <strong>Stem:</strong>
  <%= @stem.content %>
</p>

<p>
  <strong>Objective:</strong> <%= %>
  <%= @objective.objective %>
</p>

<p>
  <strong>Strength:</strong> <%= %>
  <%= @response.strength %>
</p>

<p>
  <strong>User ID:</strong> <%= %>
  <%= @response.user_id %>
</p>

<center><%= link_to 'Submit another!', new_response_path, :class => "btn btn-primary" %></center>

app/views/stems/_form.html.erb
<%= simple_form_for(@stem) do |f| %>
  <% if @stem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stem.errors.count, "error") %> prohibited this stem from being saved:</h2>

      <ul>
      <% @stem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
	<tr><td><strong>Exam</strong></td><td><%= f.input :exam_id, as: :select, collection: @exams, :label_method => :content, :value_method => :id, label:false %></td></tr>
	<tr><td><strong>Question stem</strong></td><td><%= f.text_field :content %></td></tr>
	<tr></tr>
</table>
<br>
<center>
<%= f.button :submit, "Create Question!", :class => "btn btn-primary" %>
</center>
<br>

<% end %>

app/views/stems/edit.html.erb
<h1>Editing stem</h1>

<%= render 'form' %>

<%= link_to 'Show', @stem %> |
<%= link_to 'Back', stems_path %>

app/views/stems/index.html.erb
<center><h3>Questions</h3></center>

<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th>Exam</th>
	<% if user_signed_in? %>
	<% if current_user.is_admin == 1 %>
      <th></th>
      <th></th>
      <th></th>
	<% else %>
	<% end %>
	<% else %>
	<% end %>
    </tr>
  </thead>

  <tbody>
    <% @stems.each do |stem| %>
      <tr>
        <td><%= stem.content %></td>
		<% exam = Exam.find(stem.exam_id) %>
	    <td><%= exam.content %></td>
	<% if user_signed_in? %>
	<% if current_user.is_admin == 1 %>
        <td><%= link_to 'Show', stem %></td>
        <td><%= link_to 'Edit', edit_stem_path(stem) %></td>
        <td><%= link_to 'Destroy', stem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% else %>
	<% end %>
	<% else %>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<center><%= link_to 'New Question', new_stem_path, :class => "btn btn-primary" %></center>

app/views/stems/new.html.erb
<center><h3>Create a new question!</h3></center>

<%= render 'form' %>

<!-- hide this for now...
<%= link_to 'Back', stems_path %>
-->

app/views/stems/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @stem.content %>
</p>

<p>
  <strong>Exam:</strong>
  <%= @stem.exam_id %>
</p>

<%= link_to 'Edit', edit_stem_path(@stem) %> |
<%= link_to 'Back', stems_path %>